apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jkhcu5o9s-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jkhcu5o9s-python 
  name: jkhcu5o9s-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jkhcu5o9s-python 
